# -*- coding: utf-8 -*-
"""Coffee Shop Sales code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTgMiHXLr0PVxV5kacDZE0xdYb7u76SI
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]  # Extract the uploaded file name

df = pd.read_excel(filename)

df.shape

df.head()

import matplotlib.pyplot as plt

df['day_of_week'] = df['transaction_date'].dt.day_name()

day_counts = df['day_of_week'].value_counts()

day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
day_counts = day_counts[day_order]




plt.figure(figsize=(10, 6))
ax = day_counts.plot(kind='line', color='green')
for i, value in enumerate(day_counts):
    ax.text(i, value + 1, str(value), ha='center', va='bottom', fontsize=12)

plt.title('Number of Transactions per Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Transactions')
plt.xticks(rotation=45)
plt.show()

product_sales = df.groupby('product_type')['total_sales'].sum()

top_10_products = product_sales.sort_values(ascending=False).head(10)

bottom_10_products = product_sales.sort_values(ascending=False).tail(10)

print("Top 10 Product Types")
print(top_10_products)

print("\nleast sold Product Types")
print(bottom_10_products)